"""Change avatar and background_image to Text type for large storage

Revision ID: 82a7b02b53e2
Revises: ab21d489cbaa
Create Date: 2026-01-27 13:43:12.423300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82a7b02b53e2'
down_revision: Union[str, Sequence[str], None] = 'ab21d489cbaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('avatar',
                   existing_type=sa.VARCHAR(length=255),
                   type_=sa.Text(),
                   existing_nullable=True)
        batch_op.alter_column('background_image',
                   existing_type=sa.VARCHAR(length=255),
                   type_=sa.Text(),
                   existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('background_image',
                   existing_type=sa.Text(),
                   type_=sa.VARCHAR(length=255),
                   existing_nullable=True)
        batch_op.alter_column('avatar',
                   existing_type=sa.Text(),
                   type_=sa.VARCHAR(length=255),
                   existing_nullable=True)
    # ### end Alembic commands ###
