"""Add social links and friend model

Revision ID: 8650488b6323
Revises: 82a7b02b53e2
Create Date: 2026-01-27 14:23:13.080994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8650488b6323'
down_revision: Union[str, Sequence[str], None] = '82a7b02b53e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('gitee_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gitee_url')
    op.drop_column('users', 'github_url')
    # ### end Alembic commands ###
